import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <StoreProvider>
        <html lang="en">
          <body className="bg-[#F4F2EE]">
            <div className="bg-white shadow-lg sticky top-0 z-50">
              <Header />
            </div>

            {children}
          </body>
        </html>
      </StoreProvider>
    </ClerkProvider>
  );
}
